//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eth2Overwatch {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Eth2OverwatchSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Eth2OverwatchSettings defaultInstance = ((Eth2OverwatchSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Eth2OverwatchSettings())));
        
        public static Eth2OverwatchSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ValidatorPassword {
            get {
                return ((string)(this["ValidatorPassword"]));
            }
            set {
                this["ValidatorPassword"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseLocalEth1Node
        {
            get
            {
                return ((bool)(this["UseLocalEth1Node"]));
            }
            set
            {
                this["UseLocalEth1Node"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Autostart_Validator {
            get {
                return ((bool)(this["Autostart_Validator"]));
            }
            set {
                this["Autostart_Validator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Autostart_BeaconChain {
            get {
                return ((bool)(this["Autostart_BeaconChain"]));
            }
            set {
                this["Autostart_BeaconChain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoStart_Eth1 {
            get {
                return ((bool)(this["AutoStart_Eth1"]));
            }
            set {
                this["AutoStart_Eth1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DataDir_BeaconChain {
            get {
                return ((string)(this["DataDir_BeaconChain"]));
            }
            set {
                this["DataDir_BeaconChain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DataDir_Eth1 {
            get {
                return ((string)(this["DataDir_Eth1"]));
            }
            set {
                this["DataDir_Eth1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExecutablePath_Validator {
            get {
                return ((string)(this["ExecutablePath_Validator"]));
            }
            set {
                this["ExecutablePath_Validator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExecutablePath_BeaconChain {
            get {
                return ((string)(this["ExecutablePath_BeaconChain"]));
            }
            set {
                this["ExecutablePath_BeaconChain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExecutablePath_Eth1 {
            get {
                return ((string)(this["ExecutablePath_Eth1"]));
            }
            set {
                this["ExecutablePath_Eth1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KeyPath_Validator {
            get {
                return ((string)(this["KeyPath_Validator"]));
            }
            set {
                this["KeyPath_Validator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideCommandPrompt_Validator {
            get {
                return ((bool)(this["HideCommandPrompt_Validator"]));
            }
            set {
                this["HideCommandPrompt_Validator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideCommandPrompt_BeaconChain {
            get {
                return ((bool)(this["HideCommandPrompt_BeaconChain"]));
            }
            set {
                this["HideCommandPrompt_BeaconChain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideCommandPrompt_Eth1 {
            get {
                return ((bool)(this["HideCommandPrompt_Eth1"]));
            }
            set {
                this["HideCommandPrompt_Eth1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AdditionalCommands_Validator {
            get {
                return ((string)(this["AdditionalCommands_Validator"]));
            }
            set {
                this["AdditionalCommands_Validator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AdditionalCommands_BeaconChain {
            get {
                return ((string)(this["AdditionalCommands_BeaconChain"]));
            }
            set {
                this["AdditionalCommands_BeaconChain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("--lightkdf --cache 16")]
        public string AdditionalCommands_Eth1 {
            get {
                return ((string)(this["AdditionalCommands_Eth1"]));
            }
            set {
                this["AdditionalCommands_Eth1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string Eth2_TestNet {
            get {
                return ((string)(this["Eth2_TestNet"]));
            }
            set {
                this["Eth2_TestNet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateSettings {
            get {
                return ((bool)(this["UpdateSettings"]));
            }
            set {
                this["UpdateSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WalletPath_Validator {
            get {
                return ((string)(this["WalletPath_Validator"]));
            }
            set {
                this["WalletPath_Validator"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReportPath
        {
            get
            {
                return ((string)(this["ReportPath"]));
            }
            set
            {
                this["ReportPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReportKey
        {
            get
            {
                return ((string)(this["ReportKey"]));
            }
            set
            {
                this["ReportKey"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReportLabel
        {
            get
            {
                return ((string)(this["ReportLabel"]));
            }
            set
            {
                this["ReportLabel"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastPrysmVersion {
            get {
                return ((string)(this["LastPrysmVersion"]));
            }
            set {
                this["LastPrysmVersion"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentPrysmVersion_Validator
        {
            get
            {
                return ((string)(this["CurrentPrysmVersion_Validator"]));
            }
            set
            {
                this["CurrentPrysmVersion_Validator"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseLatestVersion_Validator
        {
            get
            {
                return ((bool)(this["UseLatestVersion_Validator"]));
            }
            set
            {
                this["UseLatestVersion_Validator"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentPrysmVersion_BeaconChain
        {
            get
            {
                return ((string)(this["CurrentPrysmVersion_BeaconChain"]));
            }
            set
            {
                this["CurrentPrysmVersion_BeaconChain"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseLatestVersion_BeaconChain
        {
            get
            {
                return ((bool)(this["UseLatestVersion_BeaconChain"]));
            }
            set
            {
                this["UseLatestVersion_BeaconChain"] = value;
            }
        }
    }
}
